# Generated by Django 4.2.3 on 2024-01-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="upload",
            field=models.ImageField(blank=True, null=True, upload_to="api_images"),
        ),
    ]
